#!/bin/bash

CONTENT='
./database/Controlling.odt 
./database/createTables.odt 
./database/Einstellungen.odt 
./database/Gruppenverwaltung.odt 
./database/Import.odt 
./database/Inventur.odt 
./database/Kassenbuch.ods 
./database/Korrespondenz.odt 
./database/Kundenstamm.odt 
./database/Leistungsstamm.odt 
./database/Lieferantenstamm.odt 
./database/Kontaktestamm.odt 
./database/OP_Ausgangsrechnungen.odt 
./database/OP_Eingangsrechnungen.odt 
./database/Personalstamm.odt 
./database/Preislisten.odt 
./database/PrintArbeitsblatt.odt 
./database/PrintAusgangsrechnungen.ott 
./database/PrintInventur.odt 
./database/PrintKorrespondenz.odt
./database/PrintSerienbriefverteiler.ott
./database/PrintMahnung.odt 
./database/PrintPreisliste.odt 
./database/PrintProject.odt 
./database/PrintZahlungserinnerung.odt 
./database/PrintZahlungsziele.ott 
./database/Projekte.odt 
./database/Projekt.odt 
./database/Umsatz.odt 
./database/Alternative/PrintKorrespondenz.odt 
./database/Alternative/PrintProject.odt  
./database/Alternative/PrintMahnung.odt  
./database/Alternative/PrintZahlungserinnerung.odt 
./basic/ALADIN/dialog.xlb 
./basic/ALADIN/script.xlb 
./basic/ALADIN/Dokument.xdl 
./basic/ALADIN/Funktionen.xba 
./basic/ALADIN/Fax.xba 
./basic/ALADIN/Leistungsstamm.xdl 
./basic/ALADIN/Projekt.xdl 
./basic/ALADIN/Routinen.xba 
./basic/ALADIN/Mandant.xba 
./basic/ALADIN/Mandant.xdl 
./basic/ALADIN/ldap.xba 
./basic/ALADIN/SQL_Anweisungen.xba 
./basic/ALADIN/Startmenue.xba 
./basic/ALADIN/Start.xba 
./basic/ALADIN/Start.xdl 
./basic/ALADIN/Tabellen.xba 
./basic/ALADIN/Text.xdl 
./basic/ALADIN/Scanner.xba 
./basic/ALADIN/Scanner.xdl 
./basic/ALADIN/YajHFCSettings.xdl 
./basic/ALADIN_Global/Global.xba 
./basic/ALADIN_Global/dialog.xlb 
./basic/ALADIN_Global/script.xlb 
./ALADIN.lnk
./ALADIN.ico
./ALADIN.xpm
./ALADIN_INSTALL.odt
./openldap'

echo $CONTENT

tar cvhjf ./.git_repo/package/aladin.$(date -I).tar.bz2  $CONTENT 
zip -rv ./.git_repo/package/aladin.$(date -I).zip \ $CONTENT
